### ISSUE TITLE
Do I need a config.json file somewhere?

### ISSUE THREAD

**Issue by timsears** [deepgram/real-time-voice-bot#2]
I get a client side popup with 

`Error: You must configure your OpenAI API Key in the config.json to use the "Respond with AI" feature.`

 on  the server side I see this
`ERROR MESG Could not send. Connection not open.`

**Comment by jjmaldonis** [comment]
Hey @timsears, we are working on updating this code.

You need to set an environment variable, see the relevant code here: https://github.com/deepgram/real-time-voice-bot/blob/main/server.js#L88
